Repository MGleonMG/CBS-LF8-Verwaltung, pull requests merged in 2025-05, with the labels that each got.

#5 removing duplicates
  CBS-LF8-Verwaltung/src/verwaltung/Kurs.java
  CBS-LF8-Verwaltung/src/verwaltung/Kursteilnehmer.java
Labels: minor adjustments

#6 Bewertbar und Rabattfähig
  CBS-LF8-Verwaltung/src/verwaltung/Interfaces/Bewertbar.java
  CBS-LF8-Verwaltung/src/verwaltung/Interfaces/Rabattfaehig.java
Labels: new code

#7 code formatting
  CBS-LF8-Verwaltung/src/verwaltung/Interfaces/Bewertbar.java
  CBS-LF8-Verwaltung/src/verwaltung/Interfaces/Rabattfaehig.java
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kurs.java
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kursteilnehmer.java
Labels: minor adjustments

#8 Vererbungen & Interfaces
  CBS-LF8-Verwaltung/src/verwaltung/Abteilung.java
  CBS-LF8-Verwaltung/src/verwaltung/Besucher.java
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kurs.java
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kursteilnehmer.java
  CBS-LF8-Verwaltung/src/verwaltung/Mitarbeiter.java
  CBS-LF8-Verwaltung/src/verwaltung/main/Verwaltung.java
Labels: new code, code structure changes

#9 Programm Struktur
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kurs.java
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kursteilnehmer.java
  CBS-LF8-Verwaltung/src/verwaltung/Personen/Besucher.java
  CBS-LF8-Verwaltung/src/verwaltung/Personen/Mitarbeiter.java
  CBS-LF8-Verwaltung/src/verwaltung/struktur/Abteilung.java
  CBS-LF8-Verwaltung/src/verwaltung/struktur/Bewertbar.java
  CBS-LF8-Verwaltung/src/verwaltung/struktur/Person.java
  CBS-LF8-Verwaltung/src/verwaltung/struktur/Rabattfaehig.java
Labels: code structure changes

#10 Englische Variablen o.ä. auf Deutsch
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kurs.java
  CBS-LF8-Verwaltung/src/verwaltung/Kurs/Kursteilnehmer.java
  CBS-LF8-Verwaltung/src/verwaltung/Personen/Besucher.java
  CBS-LF8-Verwaltung/src/verwaltung/Personen/Mitarbeiter.java
  CBS-LF8-Verwaltung/src/verwaltung/struktur/Person.java
Labels: minor adjustments
